apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-prod
spec:
  acme:
    email: devops@nightingaleheart.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-prod
    solvers:
      - dns01:
          route53:
            region: eu-central-1
            hostedZoneID: Z049261517UI15V2Z4UP8
